### ISSUE TITLE
Notes on how to redirect www. to root domain

### ISSUE THREAD

**Issue by banagale** [testdrivenio/django-on-docker-letsencrypt#2]
Realized as I was going live on something that after following this guide, (and combining with the github actions setup,) I had not set up handling for the www. (I wanted all www.mydomain.com requests redirected to mydomain.com) 

How to [is teased at here](https://github.com/nginx-proxy/nginx-proxy/issues/1095) but that doesn't quite get you there using these guides. Here are some additional notes for a future traveler:

1.  Ensure both the www. and root domain have ANAME records pointing at the same IP
2.  Specify both root and www domains, delineating with a comma in `VIRTUAL_HOST`   
      
`echo VIRTUAL_HOST=www.yourdomain.com,yourdomain.com >> .env `

3.  You need the certificate on www. even though you are redirecting. So you need to also specify both root and www. domains in `LETSENCRYPT_HOST`  

`echo LETSENCRYPT_HOST=www.yourdomain.com,yourdomain.com >> .env`

4.  Add a www.yourdomain.com file to `nginx/vhost.d/` alongside `default` with the contents:  

```
    if ($request_uri !~ "^/.well-known/acme-challenge")  
    {  
      return 301 https://yourdomain.com$request_uri;  
    }  
```

5.  Ensure this file gets copied by adding the following line to `nginx/vhost.d/Dockerfile:`  
    `COPY vhost.d/www.yourdomain.com /etc/nginx/vhost.d/www.yourdomain.com`

Note, you will need to force recreation of of the nginx container. If you don't care about volumes, you can delete everything (careful!):

  
`docker-compose -f docker-compose.prod.yml down --volumes --remove-orphans`

then

`docker-compose -f docker-compose.prod.yml up -d`

The result is a letsencrypt certificate will be issued for both the www. and the root domain, the www. will 301 redirect to the main domain properly.  

Finally, if you are pulling in your domain names from an upstream `env:` in a github actions file and have specified your domain like:

```

env:
  WEB_IMAGE: docker.pkg.github.com/...
  NGINX_IMAGE: docker.pkg.github.com/...
  WEB_IMAGE_STAGING: docker.pkg.github.com/...
  NGINX_IMAGE_STAGING: docker.pkg.github.com/...
  PRODUCTION_DOMAIN: yourdomain.com
  STAGING_DOMAIN: staging.yourdomain.com
```

You can pull in the `PRODUCTION_DOMAIN` env var like so:

```
echo VIRTUAL_HOST=www.${{ env.PRODUCTION_DOMAIN }},${{ env.PRODUCTION_DOMAIN }} >> .env  
echo LETSENCRYPT_HOST=www.${{ env.PRODUCTION_DOMAIN }},${{ env.PRODUCTION_DOMAIN }} >> .env  
```
